# (실행 환경 prod 설정)
# : 배포 환경 엄격한 환경 설정

spring:
  config:
    activate: # 프로필명 설정
      on-profile: prod

  servlet:
    multipart:
      # !!!multipart 데이터량 설정!!
      maxFileSize: 50MB
      maxRequestSize: 50MB

  boot:
    admin:
      client:
        # !!!Spring Admin 정보 설정!!
        url: http://127.0.0.1:8081 # spring admin server url
        username: adminId # spring admin server Security Id
        password: adminPw # spring admin server Security Pw
        instance:
          name: Springboot Webflux Template (Prod) # spring admin UI 에서 보여질 이름 설정
          service-url: http://127.0.0.1:8080 # 현 프로젝트가 실행될 위치의 URL
  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3306/template?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: test
    password: test1234!

logging:
  file:
    name: ./logs/currentLog_prod.log # !!!Spring Admin Server 에 전달할 로그 파일 경로!!
  level:
    org.springframework.r2dbc.core: debug # R2DBC 로깅 설정

springdoc:
  swagger-ui:
    enabled: false # Swagger 문서 공개 여부

customConfig: # 프로젝트 내에서 사용하는 커스텀 설정
  # Actuator 정보 접근 허용 IP 리스트 (Spring Admin IP를 추가하세요)
  actuatorAllowIpList: 127.0.0.1, 127.0.0.3
  # Logging Filter 의 로깅 대상에서 제외할 IP 리스트 (Spring Admin IP를 추가하세요)
  loggingDenyIpList: 127.0.0.2